-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgAEvAB0OJK9Rc9Dlq
cmExt4uDQ/zx/o8pTY5uw39igS+gCgYIKoZIzj0DAQehRANCAASY2wTg6gl2BAN4
dMvM93QbUKdLOFWvpMjDqBvDaJA3SELqjUQWM/qoaxqaaYjiOr+EMTr2fl28MreH
K3CAa3Ss
-----END PRIVATE KEY-----