-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgMradntQAlWvsIObV
oNCabkTjB5PYGHzCA0qyCc+NNgqgCgYIKoZIzj0DAQehRANCAATy7sN35n63lLMV
ZdCrTnv1AxF/srIbxEl4JTzcy+cE7J9nIXzvHSRoi5atYeXUZ4OnRR75qv7Wa9CH
dtUzh41x
-----END PRIVATE KEY-----