name: Create an App Configuration
method: POST
url: '{{honoken_api_base_uri}}/api/appconfiguration'
body:
  content: "{\n    \"name\": \"Example configuration\",\n    \"passTemplateId\": \"\
    \",\n    \"scanMode\": 1,\n    \"additionalProperties\": [\n    \t{\n    \t\t\"\
    type\": \"boolean\",\n    \t\t\"name\": \"Allowed to send marketing mails?\"\n\
    \    \t},\n    \t{\n    \t\t\"type\": \"unicode\",\n    \t\t\"name\": \"Tell us\
    \ about you\"\n    \t},\n    \t{\n    \t\t\"type\": \"double\",\n    \t\t\"name\"\
    : \"Transaction value\"\n    \t}\n    \t]\n}"
  type: json
